**Privacy Policy**

Nicolas LEFEBVRE built the Freyja's Castle app as an Open Source app. This SERVICE is provided by Nicolas LEFEBVRE at no cost and is intended for use as is.

This page is used to inform visitors regarding my policies with the collection, use, and disclosure of Personal Information if anyone decided to use my Service.

If you choose to use my Service, then you agree to the collection and use of information in relation to this policy. The Personal Information that I collect is used for providing and improving the Service. I will not use or share your information with anyone except as described in this Privacy Policy.

The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which is accessible at Freyja's Castle unless otherwise defined in this Privacy Policy.

**Information Collection and Use**

this Service does not collect, use, share or retain any personally identifiable information in any way.

**Log Data**

This Service may, in case of failures, collect non-personally identifiable information (such as device type, OS version, etc.) for the purposes of diagnostic and improvement. This information will not be retained past the diagnostic period and does not identify a specific user, or contain any private information.

**Changes to This Privacy Policy**

I may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. I will notify you of any changes by posting the new Privacy Policy on this page.

This policy is effective as of 2021-11-16

**Contact Us**

If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact me at pulsars.bye_0e@icloud.com.

This privacy policy page was created at [privacypolicytemplate.net](https://privacypolicytemplate.net) and modified/generated by [App Privacy Policy Generator](https://app-privacy-policy-generator.nisrulz.com/)
